### ISSUE TITLE
Use unique IV when creating encryption/decryption cipher

### ISSUE THREAD

**Issue by jlmcdonnell** [userdashboard/dashboard#10]
https://github.com/userdashboard/dashboard/blob/80adb98fe00972883a24cf077c1cec7708d9285b/src/storage.js#L136  
  
https://stackoverflow.com/a/51125340

**Comment by benlowry** [comment]
I'm pretty sure this needs to be a fixed salt, but specified by each site instead of leaving a hardcoded value in, because the hashed values of some fields are used as indexes but I will check into that and fix this tomorrow.  Thanks!

**Comment by benlowry** [comment]
Fixed and republished.  There was already an ENV variable for the value ENCRYPTION_SECRET_IV it just wasn't implemented correctly.
